contacts:
  name: Joon Yoo
  email: joonhyoo12@gmail.com
  address: Sydney, Australia
  linkedin:
    url: https://www.linkedin.com/in/joonhyoo/
    displayText: joonhyoo
  github:
    url: https://github.com/joonhyoo/
    displayText: "@joonhyoo"
  # website:
  #   url: https://joonhyoo.dev
  #   displayText: joonhyoo.dev

position: Graduate Software Engineer

education:
  - place:
      name: University of New South Wales
      link: https://www.unsw.edu.au/
    degree: B.Sc. Computer Science
    courses:
      - COMP3121 Algorithms and Programming Techniques
      - COMP6080 Web Front-End Programming
      - COMP3511 Human Computer Interaction
      - COMP4511 User Interface Design & Construction
    complete: Dec 2025
    location: Kensington, Australia
  - place:
      name: Keio University
      link: https://www.keio.ac.jp/en/
    complete: Aug 2025
    degree: Spring Exchange Semester
    location: Tokyo, Japan
  - place:
      name: Osaka University - Center for International Education and Exchange
      link: https://ciee.osaka-u.ac.jp/en/
    degree: Winter J-Ship Program
    complete: Feb 2025
    location: Osaka, Japan

projects:
  - title: "Confluence/Rovo: Answer Your Questions"
    tech: React, Javascript, CSS, Git, Jira
    description:
      - Developer in a 6 person team that built an Atlassian Forge Application to auto-detect and respond to comments on Confluence pages.
      - The application used Gemini to generate responses, fed the page data through Qdrant's Vector Database, and was then displayed though an interactive FAQ Macro.
      - Used React to build the front-end FAQ macro and implemented email escalation in Vanilla Javascript using the SendGrid API.
  - title: Shuukan - Visual Habit Tracker (WIP)
    tech: React, CSS, SupaBase, Git
    description:
      - Built using React and Supabase, Shuukan is a responsive web app designed to help users maintain their habits.
      - "Source code can be found here: https://github.com/joonhyoo/study-calendar"
  - title: "BearGuide"
    tech: React Native, Balsamiq, Figma, Git
    description:
      - Worked in a team of 4 to create an app to help students find study spaces at UNSW.
      - Written in React Native and designed using Balsamiq and Figma wireframes.
      - Conducted usability tests to iterate the design around a user-centered design approach.
jobs:
  - position: Volleyball Coach
    company:
      name: Barker College
    type: Contract
    description:
      - Head Coach for the Boys' 4ths (2025-26)
      - Assistant Coach for the Boys' 2nds (2025-26)
      - Helped coached games and trainings for the girls' & boys' teams (2024)
    from: Oct 2024
    to: Present
    location: Sydney, Australia

volunteer:
  - position: Men's Co-Director
    company:
      name: Lynx Volleyball Club
    location: Sydney, Australia
    from: Mar 2024
    to: Dec 2025

other:
  - name: Hobbies
    items:
      - Competitive sports - Basketball & Volleyball
      - Language learning - JLPT N2 (Expected January 2026)
